[metadata]
name = "mahaloz_struct"
size = 0x10
last_change = 2022-12-20T22:00:53.562735Z

[members.0x0]
name = "some_thing"
offset = 0x0
type = ""
size = 0x4

[members.0x4]
name = "field_4"
offset = 0x4
type = ""
size = 0x4

[members.0x8]
name = "field_8"
offset = 0x8
type = ""
size = 0x4

[members.0xc]
name = "field_C"
offset = 0xc
type = ""
size = 0x4
